# Generated by Django 5.2.6 on 2025-10-11 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cancellation",
            name="canceled_quantity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cancellation",
            name="order_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_item_cancellations",
                to="api.orderitem",
            ),
        ),
        migrations.AlterField(
            model_name="cancellation",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_cancellations",
                to="api.order",
            ),
        ),
    ]
