# Generated by Django 5.2.6 on 2025-10-12 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_cancellation_canceled_quantity_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cancellation",
            old_name="created_at",
            new_name="cancelled_at",
        ),
        migrations.AlterField(
            model_name="cancellation",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_cancellations",
                to="api.order",
            ),
        ),
        migrations.AlterField(
            model_name="cancellation",
            name="order_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_item_cancellations",
                to="api.orderitem",
            ),
        ),
    ]
