# Generated by Django 5.2.6 on 2025-10-12 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_created_at_cancellation_cancelled_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cancellation",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="order_cancellations",
                to="api.order",
            ),
        ),
        migrations.AlterField(
            model_name="cancellation",
            name="order_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="order_item_cancellations",
                to="api.orderitem",
            ),
        ),
    ]
