# Generated by Django 5.2.6 on 2025-10-12 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_cancellation_order_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cancellation",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_cancellations",
                to="api.order",
            ),
        ),
    ]
