# Generated by Django 5.2.6 on 2025-10-13 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_cancellation_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="cancellation",
            name="reason",
            field=models.CharField(default="CUSTOMER_REQUEST", max_length=50),
        ),
        migrations.AlterField(
            model_name="cancellation",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cancellations",
                to="api.order",
            ),
        ),
        migrations.AlterField(
            model_name="cancellation",
            name="order_item",
            field=models.ForeignKey(
                blank=True,
                help_text="If null, it means entire order was cancelled",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cancellations",
                to="api.orderitem",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="carts",
            field=models.ManyToManyField(
                blank=True, related_name="orders", to="api.cart"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PAID", "Paid"),
                    ("REFUNDED", "Refunded"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="api.order",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.product",
            ),
        ),
    ]
