# Generated by Django 5.2.6 on 2025-10-13 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_cancellation_reason_alter_cancellation_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="carts",
            field=models.ManyToManyField(
                blank=True, related_name="cart_orders", to="api.cart"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items",
                to="api.order",
            ),
        ),
    ]
