# Generated by Django 5.2.6 on 2025-10-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_order_carts_alter_order_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
